apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: prune-deployments
  namespace: "sit-operations"
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: prune-deployments
            image: docker.repo.schwarz/openshift3/ose-cli
            command:
            - /bin/bash
            - -c
            - |
              #/bin/bash
              oc adm prune deployments --keep-younger-than=60m --confirm
            imagePullPolicy: IfNotPresent
            env:
            - name: HOME
              value: "/tmp"
          restartPolicy: OnFailure
          serviceAccountName: sit-cron-runner
