FROM registry.access.redhat.com/openshift3/ose-ansible:{{ OCP_VERSION }}

MAINTAINER {{ MAINTAINER }} <{{ MAINTAINER_EMAIL }}>

LABEL maintainer="{{ MAINTAINER }}"
LABEL summary="Provides all relevant scripts and playbooks for OCP environments"
LABEL description="With this image you can install, maintain, and debug OCP environments. It provides all relevant scripts and playbooks for these purposes."
LABEL version="{{ MAINTAINER }}"

ENV VERSION={{ MAINTAINER }}
ENV USER={{ ANSIBLE_USER }}

USER root

{% if USE_CUSTOM_REPOS == 'true' %} 
ADD  /files/repos /etc/yum.repos.d/
{% endif %}

{% if USE_CUSTOM_CERTS == 'true' %} 
RUN update-ca-trust enable \
    && update-ca-trust force-enable

ADD /files/certs /etc/pki/tls/certs/
RUN update-ca-trust extract
{% endif %}

{% if INSTALL_PKGS %} 
RUN yum clean cache all \
    && yum install -y {{ INSTALL_PKGS }} \
    && yum clean all
{% endif %}
ADD startup.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/startup.sh

# Add {{ ANSIBLE_USER }} user
RUN useradd -r -g 0 -s /sbin/nologin -c "Default User to install and maintain OCP" ${USER}

USER ${USER}

ADD /files/ssh /home/${USER}/.ssh/

ENTRYPOINT ["/usr/local/bin/startup.sh"]
