---
  - name: Fetch admin.kubeconfig from OpenShift Master
    fetch:
      src: /etc/origin/master/admin.kubeconfig
      dest: "{{ playbook_dir }}/tmp/"
      flat: yes
    delegate_to: "{{ openshift_master_hostname }}"

  - name: Create serviceAccount and roleBinding
    local_action: command {{ playbook_dir }}/scripts/misc-setup.sh 

  - name: Create cronjobs
    local_action: command {{ playbook_dir }}/scripts/cronjobs-setup.sh

  # delete the admin.kubeconfig because of security reason (it's not nedded anymore)
  - name: Delete admin.kubeconfig
    file:
      path: "{{ playbook_dir }}/tmp/admin.kubeconfig"
      state: absent