apiVersion: v1
kind: List
items:
- apiVersion: v1
  data:
    config.json: "{ \"auths\": { \"https://registry.example.com:5000\": { \"auth\":\"YourLoginToken\"},\"registry.redhat.io\":{\"auth\": \"YourLoginToken\"} } }"
  kind: ConfigMap
  metadata:
    creationTimestamp: 2019-02-07T22:01:45Z
    name: docker-config
