- hosts: localhost
  gather_facts: False
  roles:
     - role: createDirectory
     - role: createServiceAccount
     - role: createRoleBinding
     - role: createCronJobs
     - role: createRessourcesInOpenshift
       import_task: createNamespace.yaml
       when: create_namespace == 'true'
     - role: cleanup
       when: cleanup == 'true'
  vars:
        NAMESPACE: "{{ namespace }}"
        IMAGE_REGISTRY: "{{ image_registry }}"
        