apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: serviceAccounts
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: kube-state-metrics
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: node-exporter
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.alertmanager-main: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"alertmanager-main"}}'
    creationTimestamp: null
    name: alertmanager-main
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.prometheus-k8s: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"prometheus-k8s"}}'
    creationTimestamp: null
    name: prometheus-k8s
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.grafana: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana"}}'
    creationTimestamp: null
    name: grafana
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: prometheus-operator
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"cluster-monitoring-operator","namespace":"openshift-monitoring"}}
    creationTimestamp: null
    name: cluster-monitoring-operator
