apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: persistentVolumeClaims
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      alertmanager: main
      app: alertmanager
    name: alertmanager-main-db-alertmanager-main-0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: standard
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      alertmanager: main
      app: alertmanager
    name: alertmanager-main-db-alertmanager-main-1
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: standard
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      alertmanager: main
      app: alertmanager
    name: alertmanager-main-db-alertmanager-main-2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: standard
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: prometheus
      prometheus: k8s
    name: prometheus-k8s-db-prometheus-k8s-0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: standard
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: prometheus
      prometheus: k8s
    name: prometheus-k8s-db-prometheus-k8s-1
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: standard
  status: {}
